In [1]:
import pandas as pd

data 1 empty

In [6]:
df = pd.read_csv(r"c:\Users\BM\Downloads\sourcedata.txt")

EmptyDataError: No columns to parse from file

data 2

In [47]:
df = pd.read_csv(r"c:\Users\BM\Downloads\sales.csv")
df

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [54]:
df = pd.read_csv(r"c:\Users\BM\Downloads\sales.csv")
df

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [56]:
df.head(8)

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
5,6,2024-07-07,West,Laptop,Electronics,New,8,1480,0.01,11721.60
6,7,2024-01-21,East,Mouse,Accessories,Returning,6,137,0.27,600.06
7,8,2024-04-12,West,Phone,Accessories,Returning,5,1117,0.26,4132.90

In [57]:
avg_discount = df.groupby('category')['discount'].mean()
print(avg_discount)

category
Accessories    0.151111
Electronics    0.142744
Name: discount, dtype: float64

In [58]:
avg_discount = df.groupby('category')['discount'].mean()
print(avg_discount)

category
Accessories    0.151111
Electronics    0.142744
Name: discount, dtype: float64

In [59]:
top_products = df.groupby('product')['quantity'].sum().sort_values(ascending=False).head(5)
print(top_products)

product
Mouse       481
Laptop      449
Tablet      411
Keyboard    390
Phone       383
Name: quantity, dtype: int64

In [60]:
# convert date first
df['date'] = pd.to_datetime(df['date'])

# extract month
df['month'] = df['date'].dt.month

monthly_sales = df.groupby('month')['sales'].sum()

print(monthly_sales)

month
1      98673.77
2     131625.24
3      70335.46
4     150967.04
5     176939.29
6     155607.27
7     128419.96
8     194347.39
9     157999.69
10    131809.83
11    118704.40
12    151100.44
Name: sales, dtype: float64

In [61]:
sales_with_discount = df[df['discount'] > 0]['sales'].mean()
sales_without_discount = df[df['discount'] == 0]['sales'].mean()

print("Avg sales with discount:", sales_with_discount)
print("Avg sales without discount:", sales_without_discount)

Avg sales with discount: 3310.8291170431207
Avg sales without discount: 4165.846153846154

In [62]:
profit_product = df.groupby('product')['sales'].sum().idxmax()
print("Most profitable product:", profit_product)

Most profitable product: Laptop

In [63]:
customer_behavior = df.groupby('customer_type')[['quantity','sales','discount']].mean()
print(customer_behavior)

               quantity        sales  discount
customer_type
New            4.937238  3321.913640  0.140669
Returning      4.996169  3343.265977  0.152146

In [19]:
df = pd.read_csv(r"c:\Users\BM\Downloads\sales.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       500 non-null    int64
 1   date           500 non-null    str
 2   region         500 non-null    str
 3   product        500 non-null    str
 4   category       500 non-null    str
 5   customer_type  500 non-null    str
 6   quantity       500 non-null    int64
 7   price          500 non-null    int64
 8   discount       500 non-null    float64
 9   sales          500 non-null    float64
dtypes: float64(2), int64(3), str(5)
memory usage: 39.2 KB

In [20]:

df.describe()

         order_id    quantity        price   discount         sales
count  500.000000  500.000000   500.000000  500.00000    500.000000
mean   250.500000    4.968000   768.158000    0.14666   3333.059560
std    144.481833    2.569081   404.010497    0.08612   2693.185995
min      1.000000    1.000000    50.000000    0.00000     67.320000
25%    125.750000    3.000000   432.750000    0.08000   1120.867500
50%    250.500000    5.000000   742.000000    0.15000   2582.805000
75%    375.250000    7.000000  1094.500000    0.22000   4998.030000
max    500.000000    9.000000  1499.000000    0.30000  12700.800000

In [21]:
print(df.columns)

Index(['order_id', 'date', 'region', 'product', 'category', 'customer_type',
       'quantity', 'price', 'discount', 'sales'],
      dtype='str')

In [23]:
df = pd.read_csv(r"c:\Users\BM\Downloads\sales.csv")
df.rename(columns={'order_id': 'Order ID'}, inplace=True)

In [24]:
df.columns

Index(['Order ID', 'date', 'region', 'product', 'category', 'customer_type',
       'quantity', 'price', 'discount', 'sales'],
      dtype='str')

In [26]:
df.isnull().sum()

Order ID         0
date             0
region           0
product          0
category         0
customer_type    0
quantity         0
price            0
discount         0
sales            0
dtype: int64

In [27]:
df.dropna()

,Order ID,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [30]:
df.duplicated().sum()
df.drop_duplicates

<bound method DataFrame.drop_duplicates of      Order ID        date region   product     category customer_type  \
0           1  2024-04-12   East    Laptop  Electronics     Returning
1           2  2024-12-14  South   Monitor  Accessories     Returning
2           3  2024-09-27  North     Phone  Accessories           New
3           4  2024-04-16   West     Mouse  Electronics     Returning
4           5  2024-03-12   West     Phone  Electronics     Returning
..        ...         ...    ...       ...          ...           ...
495       496  2024-11-20  South     Mouse  Accessories     Returning
496       497  2024-01-04  North     Phone  Accessories     Returning
497       498  2024-01-16  South  Keyboard  Electronics     Returning
498       499  2024-10-06  North     Phone  Accessories     Returning
499       500  2024-12-01  North   Monitor  Electronics           New

     quantity  price  discount    sales
0           8    590      0.09  4295.20
1           2    262      0.18   429.68
2           5    512      0.09  2329.60
3           1    485      0.09   441.35
4           7    332      0.22  1812.72
..        ...    ...       ...      ...
495         6    314      0.23  1450.68
496         9    369      0.23  2557.17
497         6    722      0.14  3725.52
498         2   1449      0.12  2550.24
499         2    869      0.09  1581.58

[500 rows x 10 columns]>

In [31]:
df ['date'] = pd.to_datetime(df['date'])

In [32]:
print(df.dtypes)

Order ID                  int64
date             datetime64[us]
region                      str
product                     str
category                    str
customer_type               str
quantity                  int64
price                     int64
discount                float64
sales                   float64
dtype: object

In [33]:
df['quantity'] = df['quantity'].astype(int)
df['price'] = df['price'].astype(float)

In [ ]:
df['region'] = df['region'].str.strip().str.title()

In [34]:
print(df.head())
print(df.info())

   Order ID       date region  product     category customer_type  quantity  \
0         1 2024-04-12   East   Laptop  Electronics     Returning         8
1         2 2024-12-14  South  Monitor  Accessories     Returning         2
2         3 2024-09-27  North    Phone  Accessories           New         5
3         4 2024-04-16   West    Mouse  Electronics     Returning         1
4         5 2024-03-12   West    Phone  Electronics     Returning         7

   price  discount    sales
0  590.0      0.09  4295.20
1  262.0      0.18   429.68
2  512.0      0.09  2329.60
3  485.0      0.09   441.35
4  332.0      0.22  1812.72
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       500 non-null    int64
 1   date           500 non-null    datetime64[us]
 2   region         500 non-null    str
 3   product        500 non-null    str
 4   category       500 non-null    str
 5   customer_type  500 non-null    str
 6   quantity       500 non-null    int64
 7   price          500 non-null    float64
 8   discount       500 non-null    float64
 9   sales          500 non-null    float64
dtypes: datetime64[us](1), float64(3), int64(2), str(4)
memory usage: 39.2 KB
None

data 3

In [48]:
df = pd.read_csv(r"c:\Users\BM\Downloads\merged_data.csv")
df

,date,region,product,category,customer_type,quantity,price,sales,customer_rating,sales_category
0,2024-04-12,East,Laptop,Electronics,Returning,8,590,4295.20,1,very high
1,2024-12-14,South,Monitor,Accessories,Returning,2,262,429.68,1,medium
2,2024-09-27,North,Phone,Accessories,New,5,512,2329.60,2,very high
3,2024-04-16,West,Mouse,Electronics,Returning,1,485,441.35,1,medium
4,2024-03-12,West,Phone,Electronics,Returning,7,332,1812.72,4,very high
...,...,...,...,...,...,...,...,...,...,...
495,2024-11-20,South,Mouse,Accessories,Returning,6,314,1450.68,3,very high
496,2024-01-04,North,Phone,Accessories,Returning,9,369,2557.17,4,very high
497,2024-01-16,South,Keyboard,Electronics,Returning,6,722,3725.52,4,very high
498,2024-10-06,North,Phone,Accessories,Returning,2,1449,2550.24,1,very high
499,2024-12-01,North,Monitor,Electronics,New,2,869,1581.58,1,very high

In [50]:
df = pd.read_csv(r"c:\Users\BM\Downloads\merged_data.csv")
df
# create sales column
df['sales'] = df['quantity'] * df['price']

# total sales by region
region_sales = df.groupby('region')['sales'].sum()

print(region_sales)

# region with highest sales
print("Highest sales region:", region_sales.idxmax())# create sales column
df['sales'] = df['quantity'] * df['price']

# total sales by region
region_sales = df.groupby('region')['sales'].sum()

print(region_sales)

# region with highest sales
print("Highest sales region:", region_sales.idxmax())


avg_rating = df.groupby('customer_type')['customer_rating'].mean()
print(avg_rating)

region
East     490986
North    607227
South    418989
West     433493
Name: sales, dtype: int64
Highest sales region: North
region
East     490986
North    607227
South    418989
West     433493
Name: sales, dtype: int64
Highest sales region: North
customer_type
New          2.472803
Returning    2.486590
Name: customer_rating, dtype: float64

In [52]:
avg_rating = df.groupby('customer_type')['customer_rating'].mean()
print(avg_rating)

customer_type
New          2.472803
Returning    2.486590
Name: customer_rating, dtype: float64

In [35]:
import pandas as pd
df = pd.read_csv(r"c:\Users\BM\Downloads\merged_data.csv")
print(df.head(8))
print(df.info())
print(df.describe())
print(df.columns)
df.rename(columns={'price': 'PRICE'}, inplace=True)
print(df.columns)

         date region  product     category customer_type  quantity  price  \
0  2024-04-12   East   Laptop  Electronics     Returning         8    590
1  2024-12-14  South  Monitor  Accessories     Returning         2    262
2  2024-09-27  North    Phone  Accessories           New         5    512
3  2024-04-16   West    Mouse  Electronics     Returning         1    485
4  2024-03-12   West    Phone  Electronics     Returning         7    332
5  2024-07-07   West   Laptop  Electronics           New         8   1480
6  2024-01-21   East    Mouse  Accessories     Returning         6    137
7  2024-04-12   West    Phone  Accessories     Returning         5   1117

      sales  customer_rating sales_category
0   4295.20                1      very high
1    429.68                1         medium
2   2329.60                2      very high
3    441.35                1         medium
4   1812.72                4      very high
5  11721.60                2            NaN
6    600.06                1           high
7   4132.90                2      very high
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             500 non-null    str
 1   region           500 non-null    str
 2   product          500 non-null    str
 3   category         500 non-null    str
 4   customer_type    500 non-null    str
 5   quantity         500 non-null    int64
 6   price            500 non-null    int64
 7   sales            500 non-null    float64
 8   customer_rating  500 non-null    int64
 9   sales_category   375 non-null    str
dtypes: float64(1), int64(3), str(6)
memory usage: 39.2 KB
None
         quantity        price         sales  customer_rating
count  500.000000   500.000000    500.000000       500.000000
mean     4.968000   768.158000   3333.059560         2.480000
std      2.569081   404.010497   2693.185995         1.118975
min      1.000000    50.000000     67.320000         1.000000
25%      3.000000   432.750000   1120.867500         1.000000
50%      5.000000   742.000000   2582.805000         2.500000
75%      7.000000  1094.500000   4998.030000         3.000000
max      9.000000  1499.000000  12700.800000         4.000000
Index(['date', 'region', 'product', 'category', 'customer_type', 'quantity',
       'price', 'sales', 'customer_rating', 'sales_category'],
      dtype='str')
Index(['date', 'region', 'product', 'category', 'customer_type', 'quantity',
       'PRICE', 'sales', 'customer_rating', 'sales_category'],
      dtype='str')

In [37]:
print(df.isnull().sum())

# Handle missing values (example)
df = df.dropna()   # remove rows with missing values
# OR
# df.fillna(0, inplace=True)

# Check duplicate rows
print("Duplicate rows:", df.duplicated().sum())

# Remove duplicates
df = df.drop_duplicates()

# Convert 'date' column to datetime
df['date'] = pd.to_datetime(df['date'])

# Check data types
print(df.dtypes)

# Standardize 'region' values
df['region'] = df['region'].str.strip().str.title()

# Final check
print(df.head())
print(df.info())

date               0
region             0
product            0
category           0
customer_type      0
quantity           0
PRICE              0
sales              0
customer_rating    0
sales_category     0
dtype: int64
Duplicate rows: 0
date               datetime64[us]
region                        str
product                       str
category                      str
customer_type                 str
quantity                    int64
PRICE                       int64
sales                     float64
customer_rating             int64
sales_category                str
dtype: object
        date region  product     category customer_type  quantity  PRICE  \
0 2024-04-12   East   Laptop  Electronics     Returning         8    590
1 2024-12-14  South  Monitor  Accessories     Returning         2    262
2 2024-09-27  North    Phone  Accessories           New         5    512
3 2024-04-16   West    Mouse  Electronics     Returning         1    485
4 2024-03-12   West    Phone  Electronics     Returning         7    332

     sales  customer_rating sales_category
0  4295.20                1      very high
1   429.68                1         medium
2  2329.60                2      very high
3   441.35                1         medium
4  1812.72                4      very high
<class 'pandas.DataFrame'>
Index: 375 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             375 non-null    datetime64[us]
 1   region           375 non-null    str
 2   product          375 non-null    str
 3   category         375 non-null    str
 4   customer_type    375 non-null    str
 5   quantity         375 non-null    int64
 6   PRICE            375 non-null    int64
 7   sales            375 non-null    float64
 8   customer_rating  375 non-null    int64
 9   sales_category   375 non-null    str
dtypes: datetime64[us](1), float64(1), int64(3), str(5)
memory usage: 32.2 KB
None

data 4

In [10]:
df = pd.read_csv(r"c:\Users\BM\Downloads\customers.csv")

In [39]:
df = pd.read_csv(r"c:\Users\BM\Downloads\customers.csv")
df
print(df.head(8))
print(df.info())
print(df.describe())
print(df.columns)
df.rename(columns={'customer_rating': 'Customer_Rating'}, inplace=True)
print(df.columns)

   order_id  customer_rating
0         1                1
1         2                1
2         3                2
3         4                1
4         5                4
5         6                2
6         7                1
7         8                2
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         500 non-null    int64
 1   customer_rating  500 non-null    int64
dtypes: int64(2)
memory usage: 7.9 KB
None
         order_id  customer_rating
count  500.000000       500.000000
mean   250.500000         2.480000
std    144.481833         1.118975
min      1.000000         1.000000
25%    125.750000         1.000000
50%    250.500000         2.500000
75%    375.250000         3.000000
max    500.000000         4.000000
Index(['order_id', 'customer_rating'], dtype='str')
Index(['order_id', 'Customer_Rating'], dtype='str')

In [40]:
print(df.isnull().sum())

# Handle missing values (example)
df = df.dropna()   # remove rows with missing values
# OR
# df.fillna(0, inplace=True)

# Check duplicate rows
print("Duplicate rows:", df.duplicated().sum())

# Remove duplicates
df = df.drop_duplicates()

# Check data types
print(df.dtypes)

# Final check
print(df.head())
print(df.info())

order_id           0
Customer_Rating    0
dtype: int64
Duplicate rows: 0
order_id           int64
Customer_Rating    int64
dtype: object
   order_id  Customer_Rating
0         1                1
1         2                1
2         3                2
3         4                1
4         5                4
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         500 non-null    int64
 1   Customer_Rating  500 non-null    int64
dtypes: int64(2)
memory usage: 7.9 KB
None

In [41]:
# create sales column
df['sales'] = df['quantity'] * df['price']

# total sales by region
region_sales = df.groupby('region')['sales'].sum()

print(region_sales)

# region with highest sales
print("Highest sales region:", region_sales.idxmax())

KeyError: 'quantity'