In [4]:
import pandas as pd
print(pd.__version__)

3.0.1

In [5]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Age": [20, 22, 21],
    "City": ["Lahore", "Karachi", "Islamabad"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age       City
0    Ali   20     Lahore
1   Sara   22    Karachi
2  Ahmed   21  Islamabad

In [6]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Age": [20, 22, 21]
}

df = pd.DataFrame(data)

print(df["Name"])

0      Ali
1     Sara
2    Ahmed
Name: Name, dtype: str

In [7]:
import pandas as pd

data = {
    "Marks": [80, 90, 70, 85]
}

df = pd.DataFrame(data)

print("Average:", df["Marks"].mean())
print("Maximum:", df["Marks"].max())

Average: 81.25
Maximum: 90

In [7]:
import pandas as pd

# List of dictionaries
data = [
    {"Name": "Ali", "Age": 20, "City": "Lahore"},
    {"Name": "Sara", "Age": 22, "City": "Karachi"},
    {"Name": "Ahmed", "Age": 21, "City": "Islamabad"}
]

# Convert to DataFrame
df = pd.DataFrame(data)

print(df)

    Name  Age       City
0    Ali   20     Lahore
1   Sara   22    Karachi
2  Ahmed   21  Islamabad

In [11]:
import pandas as pd
df = pd.DataFrame(0, index=range(10), columns=range(21))
print(df)

   0   1   2   3   4   5   6   7   8   9   ...  11  12  13  14  15  16  17  \
0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
1   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
2   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
3   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
4   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
5   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
6   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
7   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
8   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
9   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0

   18  19  20
0   0   0   0
1   0   0   0
2   0   0   0
3   0   0   0
4   0   0   0
5   0   0   0
6   0   0   0
7   0   0   0
8   0   0   0
9   0   0   0

[10 rows x 21 columns]

In [ ]:
import pandas as pd
import numpy as np
data = np.random.randint(1, 100, (10, 21))
df = pd.DataFrame(data)
print(df)

   0   1   2   3   4   5   6   7   8   9   ...  11  12  13  14  15  16  17  \
0  72  20  36  88  29  23   7  39  62  97  ...  97  11  81  56  27  63  16
1  49  76   8  63  52  11  10  84  95  96  ...  84  21  48  24  81  50  43
2  58  29  50  75  18  73  98  75  80  60  ...  12  97  95  51  98  22  29
3  22  80  86   7  15  20  13  31  27  55  ...   9  10  15  50  81  79  33
4  55  10   9  52  45  79  49  66  77  41  ...  13  27  16  20  34  52  85
5  63   6  21  13  71   1  95  56  24  63  ...  13  50  35  69  10  24  85
6  77  29   7  13  82  64  12  70  22  72  ...  73  39  38  53  29  99   7
7  26  43   6  98   1  32  32  84  52  47  ...  16  71  38   4   5  92  86
8   3  26  14  76  62  69  20   9  50  42  ...  72  80  65  31   4  12  69
9  89  61  67   3  75  18  60  36  69  77  ...  62  96  49  90   8  41  99

   18  19  20
0  88  60  95
1  17  53  87
2   4  37  23
3  44  52   5
4   9  86  29
5  51  54  34
6  14  29  44
7  94  31  10
8  74  25  29
9  95  81  61

[10 rows x 21 columns]

In [5]:
import pandas as pd
import numpy as np
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])
s3 = pd.Series({"a": 1, "b": 2, "c": 3})
s4 = pd.Series(np.random.randint(1, 100, 5))
print(s1.values)
print(s2.index)
print(s3.keys)
print(s4.dtype)

[1 2 3 4 5]
RangeIndex(start=0, stop=5, step=1)
<bound method Series.keys of a    1
b    2
c    3
dtype: int64>
int32

In [10]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed", "Zainab"],
    "Age": [20, 22, 21, 23],
    "City": ["Lahore", "Karachi", "Islamabad", "Multan"]
})
df2 = pd.DataFrame([
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Paris'}
])
df3 = pd.DataFrame(np.random.randn(4, 3),
                    columns=['A', 'B', 'C'],
                    index=['Row1', 'Row2', 'Row3', 'Row4'])
df2['Age'].unique()
print(df1)
print(df2)
print(df3)

     Name  Age       City
0     Ali   20     Lahore
1    Sara   22    Karachi
2   Ahmed   21  Islamabad
3  Zainab   23     Multan
    Name  Age      City
0  Alice   25  New York
1    Bob   30     Paris
             A         B         C
Row1 -2.352136 -0.658735  0.783597
Row2  0.805039 -0.549729 -1.607267
Row3 -0.361103 -0.502449  2.538532
Row4  0.862821  0.339278  0.668667

In [9]:
list=['a','b','c','d','w']
print(list)
d2 = pd.DataFrame(list)
print(d2)

['a', 'b', 'c', 'd', 'w']
   0
0  a
1  b
2  c
3  d
4  w

In [2]:
import pandas as pd
df = pd.read_csv(r"c:\Users\BM\Downloads\weather.csv")
print(df.describe())
print(df.info())
print(df.isnull().sum().sum())
print(df.duplicated())
print(df.drop_duplicates())
print(df.iloc[2])
print(df.loc[0:2])
print(df.value_counts())
print(sorted(df['Time'].unique()))
print(df.merge(df, on='Description', how='inner'))
print(df.ffill())

       MIN temp (deg Celcius)                       Location       Time  \
count                      31                             31         31
unique                      5                              2          2
top                        19  Bharsul, India 10-day Weather  23:04 IST
freq                       12                             30         30

              Wind MAX temp (deg Celcius) Description Precipitation (in %)  \
count           31                     31          31                   31
unique          16                      6           4                    2
top     NE 2 km/h                      33       Sunny                    0
freq             2                     10          20                   30

          Date                                      Other Details  \
count       31                                                 31
unique      16                                                 16
top     18 OCT  Generally clear. Low 22ºC. Winds NE and variable.
freq         2                                                  2

       Humidity (in %)  Day
count               31   31
unique               9    9
top                 29  Fri
freq                 8    4
<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   MIN temp (deg Celcius)  31 non-null     str
 1   Location                31 non-null     str
 2   Time                    31 non-null     str
 3   Wind                    31 non-null     str
 4   MAX temp (deg Celcius)  31 non-null     str
 5   Description             31 non-null     str
 6   Precipitation (in %)    31 non-null     str
 7   Date                    31 non-null     str
 8   Other Details           31 non-null     str
 9   Humidity (in %)         31 non-null     str
 10  Day                     31 non-null     str
dtypes: str(11)
memory usage: 2.8 KB
None
0
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
dtype: bool
    MIN temp (deg Celcius)                       Location       Time  \
0                       22  Bharsul, India 10-day Weather  23:04 IST
1                       22  Bharsul, India 10-day Weather  23:04 IST
2                       22  Bharsul, India 10-day Weather  23:04 IST
3                       21  Bharsul, India 10-day Weather  23:04 IST
4                       21  Bharsul, India 10-day Weather  23:04 IST
5                       21  Bharsul, India 10-day Weather  23:04 IST
6                       21  Bharsul, India 10-day Weather  23:04 IST
7                       20  Bharsul, India 10-day Weather  23:04 IST
8                       20  Bharsul, India 10-day Weather  23:04 IST
9                       19  Bharsul, India 10-day Weather  23:04 IST
10                      19  Bharsul, India 10-day Weather  23:04 IST
11                      19  Bharsul, India 10-day Weather  23:04 IST
12                      19  Bharsul, India 10-day Weather  23:04 IST
13                      19  Bharsul, India 10-day Weather  23:04 IST
14                      19  Bharsul, India 10-day Weather  23:04 IST
15  MIN temp (deg Celcius)                       Location       Time

           Wind  MAX temp (deg Celcius)   Description  Precipitation (in %)  \
0    NE 2 km/h                       --         Clear                     0
1   NNW 7 km/h                       36  Mostly Sunny                     0
2   SSW 5 km/h                       35         Sunny                     0
3   WSW 9 km/h                       36         Sunny                     0
4     N 9 km/h                       35         Sunny                     0
5     W 8 km/h                       35         Sunny                     0
6   SSE 7 km/h                       34  Mostly Sunny                     0
7   SSW 9 km/h                       34  Mostly Sunny                     0
8     E 7 km/h                       34  Mostly Sunny                     0
9   NE 10 km/h                       34         Sunny                     0
10   NE 7 km/h                       33         Sunny                     0
11  ENE 6 km/h                       33         Sunny                     0
12    E 6 km/h                       33         Sunny                     0
13  ESE 5 km/h                       33         Sunny                     0
14  NNW 5 km/h                       33         Sunny                     0
15         Wind  MAX temp (deg Celcius)   Description  Precipitation (in %)

      Date                                      Other Details  \
0   18 OCT  Generally clear. Low 22ºC. Winds NE and variable.
1   19 OCT  Generally clear. High 36ºC. Winds NNW and vari...
2   20 OCT  Generally clear. High 35ºC. Winds SSW and vari...
3   21 OCT  Generally clear. High 36ºC. Winds WSW and vari...
4   22 OCT  Generally clear. High 35ºC. Winds N and variable.
5   23 OCT  Generally clear. High 35ºC. Winds W and variable.
6   24 OCT  Generally clear. High 34ºC. Winds SSE and vari...
7   25 OCT  Generally clear. High 34ºC. Winds SSW and vari...
8   26 OCT  Generally clear. High 34ºC. Winds E and variable.
9   27 OCT  Generally clear. High 34ºC. Winds NE at 10 to ...
10  28 OCT  Generally clear. High 33ºC. Winds NE and varia...
11  29 OCT  Generally clear. High 33ºC. Winds ENE and vari...
12  30 OCT  Generally clear. High 33ºC. Winds E and variable.
13  31 OCT  Generally clear. High 33ºC. Winds ESE and vari...
14   1 NOV  Generally clear. High 33ºC. Winds NNW and vari...
15    Date                                      Other Details

    Humidity (in %)      Day
0                48  Tonight
1                29      Fri
2                29      Sat
3                32      Sun
4                31      Mon
5                29      Tue
6                28      Wed
7                27      Thu
8                29      Fri
9                30      Sat
10               28      Sun
11               26      Mon
12               27      Tue
13               27      Wed
14               28      Thu
15  Humidity (in %)      Day
MIN temp (deg Celcius)                                                   22
Location                                      Bharsul, India 10-day Weather
Time                                                              23:04 IST
Wind                                                            SSW 5 km/h
MAX temp (deg Celcius)                                                   35
Description                                                           Sunny
Precipitation (in %)                                                      0
Date                                                                 20 OCT
Other Details             Generally clear. High 35ºC. Winds SSW and vari...
Humidity (in %)                                                          29
Day                                                                     Sat
Name: 2, dtype: str
  MIN temp (deg Celcius)                       Location       Time  \
0                     22  Bharsul, India 10-day Weather  23:04 IST
1                     22  Bharsul, India 10-day Weather  23:04 IST
2                     22  Bharsul, India 10-day Weather  23:04 IST

          Wind MAX temp (deg Celcius)   Description Precipitation (in %)  \
0   NE 2 km/h                      --         Clear                    0
1  NNW 7 km/h                      36  Mostly Sunny                    0
2  SSW 5 km/h                      35         Sunny                    0

     Date                                      Other Details Humidity (in %)  \
0  18 OCT  Generally clear. Low 22ºC. Winds NE and variable.              48
1  19 OCT  Generally clear. High 36ºC. Winds NNW and vari...              29
2  20 OCT  Generally clear. High 35ºC. Winds SSW and vari...              29

       Day
0  Tonight
1      Fri
2      Sat
MIN temp (deg Celcius)  Location                       Time       Wind         MAX temp (deg Celcius)  Description   Precipitation (in %)  Date    Other Details                                           Humidity (in %)  Day
22                      Bharsul, India 10-day Weather  23:04 IST  NE 2 km/h    --                      Clear         0                     18 OCT  Generally clear. Low 22ºC. Winds NE and variable.       48               Tonight    2
                                                                  NNW 7 km/h   36                      Mostly Sunny  0                     19 OCT  Generally clear. High 36ºC. Winds NNW and variable.     29               Fri        2
                                                                  SSW 5 km/h   35                      Sunny         0                     20 OCT  Generally clear. High 35ºC. Winds SSW and variable.     29               Sat        2
21                      Bharsul, India 10-day Weather  23:04 IST  WSW 9 km/h   36                      Sunny         0                     21 OCT  Generally clear. High 36ºC. Winds WSW and variable.     32               Sun        2
                                                                  N 9 km/h     35                      Sunny         0                     22 OCT  Generally clear. High 35ºC. Winds N and variable.       31               Mon        2
                                                                  W 8 km/h     35                      Sunny         0                     23 OCT  Generally clear. High 35ºC. Winds W and variable.       29               Tue        2
                                                                  SSE 7 km/h   34                      Mostly Sunny  0                     24 OCT  Generally clear. High 34ºC. Winds SSE and variable.     28               Wed        2
20                      Bharsul, India 10-day Weather  23:04 IST  SSW 9 km/h   34                      Mostly Sunny  0                     25 OCT  Generally clear. High 34ºC. Winds SSW and variable.     27               Thu        2
                                                                  E 7 km/h     34                      Mostly Sunny  0                     26 OCT  Generally clear. High 34ºC. Winds E and variable.       29               Fri        2
19                      Bharsul, India 10-day Weather  23:04 IST  NE 10 km/h   34                      Sunny         0                     27 OCT  Generally clear. High 34ºC. Winds NE at 10 to 15 km/h.  30               Sat        2
                                                                  NE 7 km/h    33                      Sunny         0                     28 OCT  Generally clear. High 33ºC. Winds NE and variable.      28               Sun        2
                                                                  ENE 6 km/h   33                      Sunny         0                     29 OCT  Generally clear. High 33ºC. Winds ENE and variable.     26               Mon        2
                                                                  E 6 km/h     33                      Sunny         0                     30 OCT  Generally clear. High 33ºC. Winds E and variable.       27               Tue        2
                                                                  ESE 5 km/h   33                      Sunny         0                     31 OCT  Generally clear. High 33ºC. Winds ESE and variable.     27               Wed        2
                                                                  NNW 5 km/h   33                      Sunny         0                     1 NOV   Generally clear. High 33ºC. Winds NNW and variable.     28               Thu        2
MIN temp (deg Celcius)  Location                       Time       Wind         MAX temp (deg Celcius)  Description   Precipitation (in %)  Date    Other Details                                           Humidity (in %)  Day        1
Name: count, dtype: int64
['23:04 IST', 'Time']
    MIN temp (deg Celcius)_x                     Location_x     Time_x  \
0                         22  Bharsul, India 10-day Weather  23:04 IST
1                         22  Bharsul, India 10-day Weather  23:04 IST
2                         22  Bharsul, India 10-day Weather  23:04 IST
3                         22  Bharsul, India 10-day Weather  23:04 IST
4                         22  Bharsul, India 10-day Weather  23:04 IST
..                       ...                            ...        ...
464                       19  Bharsul, India 10-day Weather  23:04 IST
465                       19  Bharsul, India 10-day Weather  23:04 IST
466                       19  Bharsul, India 10-day Weather  23:04 IST
467                       19  Bharsul, India 10-day Weather  23:04 IST
468                       19  Bharsul, India 10-day Weather  23:04 IST

          Wind_x MAX temp (deg Celcius)_x   Description  \
0     NE 2 km/h                        --         Clear
1     NE 2 km/h                        --         Clear
2    NNW 7 km/h                        36  Mostly Sunny
3    NNW 7 km/h                        36  Mostly Sunny
4    NNW 7 km/h                        36  Mostly Sunny
..           ...                      ...           ...
464  NNW 5 km/h                        33         Sunny
465  NNW 5 km/h                        33         Sunny
466  NNW 5 km/h                        33         Sunny
467  NNW 5 km/h                        33         Sunny
468  NNW 5 km/h                        33         Sunny

    Precipitation (in %)_x  Date_x  \
0                        0  18 OCT
1                        0  18 OCT
2                        0  19 OCT
3                        0  19 OCT
4                        0  19 OCT
..                     ...     ...
464                      0   1 NOV
465                      0   1 NOV
466                      0   1 NOV
467                      0   1 NOV
468                      0   1 NOV

                                       Other Details_x Humidity (in %)_x  ...  \
0    Generally clear. Low 22ºC. Winds NE and variable.                48  ...
1    Generally clear. Low 22ºC. Winds NE and variable.                48  ...
2    Generally clear. High 36ºC. Winds NNW and vari...                29  ...
3    Generally clear. High 36ºC. Winds NNW and vari...                29  ...
4    Generally clear. High 36ºC. Winds NNW and vari...                29  ...
..                                                 ...               ...  ...
464  Generally clear. High 33ºC. Winds NNW and vari...                28  ...
465  Generally clear. High 33ºC. Winds NNW and vari...                28  ...
466  Generally clear. High 33ºC. Winds NNW and vari...                28  ...
467  Generally clear. High 33ºC. Winds NNW and vari...                28  ...
468  Generally clear. High 33ºC. Winds NNW and vari...                28  ...

    MIN temp (deg Celcius)_y                     Location_y     Time_y  \
0                         22  Bharsul, India 10-day Weather  23:04 IST
1                         22  Bharsul, India 10-day Weather  23:04 IST
2                         22  Bharsul, India 10-day Weather  23:04 IST
3                         21  Bharsul, India 10-day Weather  23:04 IST
4                         20  Bharsul, India 10-day Weather  23:04 IST
..                       ...                            ...        ...
464                       19  Bharsul, India 10-day Weather  23:04 IST
465                       19  Bharsul, India 10-day Weather  23:04 IST
466                       19  Bharsul, India 10-day Weather  23:04 IST
467                       19  Bharsul, India 10-day Weather  23:04 IST
468                       19  Bharsul, India 10-day Weather  23:04 IST

          Wind_y MAX temp (deg Celcius)_y Precipitation (in %)_y  Date_y  \
0     NE 2 km/h                        --                      0  18 OCT
1     NE 2 km/h                        --                      0  18 OCT
2    NNW 7 km/h                        36                      0  19 OCT
3    SSE 7 km/h                        34                      0  24 OCT
4    SSW 9 km/h                        34                      0  25 OCT
..           ...                      ...                    ...     ...
464   NE 7 km/h                        33                      0  28 OCT
465  ENE 6 km/h                        33                      0  29 OCT
466    E 6 km/h                        33                      0  30 OCT
467  ESE 5 km/h                        33                      0  31 OCT
468  NNW 5 km/h                        33                      0   1 NOV

                                       Other Details_y Humidity (in %)_y  \
0    Generally clear. Low 22ºC. Winds NE and variable.                48
1    Generally clear. Low 22ºC. Winds NE and variable.                48
2    Generally clear. High 36ºC. Winds NNW and vari...                29
3    Generally clear. High 34ºC. Winds SSE and vari...                28
4    Generally clear. High 34ºC. Winds SSW and vari...                27
..                                                 ...               ...
464  Generally clear. High 33ºC. Winds NE and varia...                28
465  Generally clear. High 33ºC. Winds ENE and vari...                26
466  Generally clear. High 33ºC. Winds E and variable.                27
467  Generally clear. High 33ºC. Winds ESE and vari...                27
468  Generally clear. High 33ºC. Winds NNW and vari...                28

       Day_y
0    Tonight
1    Tonight
2        Fri
3        Wed
4        Thu
..       ...
464      Sun
465      Mon
466      Tue
467      Wed
468      Thu

[469 rows x 21 columns]
    MIN temp (deg Celcius)                       Location       Time  \
0                       22  Bharsul, India 10-day Weather  23:04 IST
1                       22  Bharsul, India 10-day Weather  23:04 IST
2                       22  Bharsul, India 10-day Weather  23:04 IST
3                       21  Bharsul, India 10-day Weather  23:04 IST
4                       21  Bharsul, India 10-day Weather  23:04 IST
5                       21  Bharsul, India 10-day Weather  23:04 IST
6                       21  Bharsul, India 10-day Weather  23:04 IST
7                       20  Bharsul, India 10-day Weather  23:04 IST
8                       20  Bharsul, India 10-day Weather  23:04 IST
9                       19  Bharsul, India 10-day Weather  23:04 IST
10                      19  Bharsul, India 10-day Weather  23:04 IST
11                      19  Bharsul, India 10-day Weather  23:04 IST
12                      19  Bharsul, India 10-day Weather  23:04 IST
13                      19  Bharsul, India 10-day Weather  23:04 IST
14                      19  Bharsul, India 10-day Weather  23:04 IST
15  MIN temp (deg Celcius)                       Location       Time
16                      22  Bharsul, India 10-day Weather  23:04 IST
17                      22  Bharsul, India 10-day Weather  23:04 IST
18                      22  Bharsul, India 10-day Weather  23:04 IST
19                      21  Bharsul, India 10-day Weather  23:04 IST
20                      21  Bharsul, India 10-day Weather  23:04 IST
21                      21  Bharsul, India 10-day Weather  23:04 IST
22                      21  Bharsul, India 10-day Weather  23:04 IST
23                      20  Bharsul, India 10-day Weather  23:04 IST
24                      20  Bharsul, India 10-day Weather  23:04 IST
25                      19  Bharsul, India 10-day Weather  23:04 IST
26                      19  Bharsul, India 10-day Weather  23:04 IST
27                      19  Bharsul, India 10-day Weather  23:04 IST
28                      19  Bharsul, India 10-day Weather  23:04 IST

In [3]:
pd.read_csv(r"c:\Users\BM\Downloads\generic-food.csv")
df = pd.read_csv(r"c:\Users\BM\Downloads\generic-food.csv")
print(df.head(2))
print(df.describe())
print(df.info())

       FOOD NAME                 SCIENTIFIC NAME             GROUP SUB GROUP
0       Angelica                Angelica keiskei  Herbs and Spices     Herbs
1  Savoy cabbage  Brassica oleracea var. sabauda        Vegetables  Cabbages
       FOOD NAME  SCIENTIFIC NAME          GROUP SUB GROUP
count        906              648            903       903
unique       906              639             24       123
top     Angelica  Capsicum annuum  Aquatic foods    Fishes
freq           1                6            166       111
<class 'pandas.DataFrame'>
RangeIndex: 906 entries, 0 to 905
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FOOD NAME        906 non-null    str
 1   SCIENTIFIC NAME  648 non-null    str
 2   GROUP            903 non-null    str
 3   SUB GROUP        903 non-null    str
dtypes: str(4)
memory usage: 28.4 KB
None

In [22]:
df = pd.read_csv(r"c:\Users\BM\Downloads\generic-food.csv")
df.describe()

       FOOD NAME  SCIENTIFIC NAME          GROUP SUB GROUP
count        906              648            903       903
unique       906              639             24       123
top     Angelica  Capsicum annuum  Aquatic foods    Fishes
freq           1                6            166       111

In [40]:
print(sorted(df['Description']))

['Clear', 'Clear', 'Description', 'Mostly Sunny', 'Mostly Sunny', 'Mostly Sunny', 'Mostly Sunny', 'Mostly Sunny', 'Mostly Sunny', 'Mostly Sunny', 'Mostly Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny']

In [41]:
print(df.groupby('Description'))

<pandas.api.typing.DataFrameGroupBy object at 0x00000197355203D0>

pandas task

In [ ]:
import pandas as pd
df = pd.read_csv(r"c:\Users\BM\Downloads\data.csv")
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [3]:
print(df.head(5))

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [4]:
print(df.tail(5))

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [5]:
print(df.shape)

(32, 5)

In [6]:
print(df.columns)

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='str')

In [7]:
print(df.columns.tolist())

['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories']

In [8]:
print(df.dtypes)

Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [9]:
print(df.describe())

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [2]:
import pandas as pd
df = pd.read_csv(r"c:\Users\BM\Downloads\data.csv")
print(df['Pulse'].max())

130

In [3]:
print(df["Duration"].min())

30

In [4]:
print(df["Calories"].mean())

304.68

task 2 data clean

In [10]:
df["Date"] = pd.to_datetime(df["Date"], format="mixed")
print(df["Date"])

0    2020-12-01
1    2020-12-02
2    2020-12-03
3    2020-12-04
4    2020-12-05
5    2020-12-06
6    2020-12-07
7    2020-12-08
8    2020-12-09
9    2020-12-10
10   2020-12-11
11   2020-12-12
12   2020-12-12
13   2020-12-13
14   2020-12-14
15   2020-12-15
16   2020-12-16
17   2020-12-17
18   2020-12-18
19   2020-12-19
20   2020-12-20
21   2020-12-21
22          NaT
23   2020-12-23
24   2020-12-24
25   2020-12-25
26   2020-12-26
27   2020-12-27
28   2020-12-28
29   2020-12-29
30   2020-12-30
31   2020-12-31
Name: Date, dtype: datetime64[us]

In [11]:
print(df.isnull().sum())

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [15]:
print(df["Calories"].fillna(df["Calories"].mean()))

0     409.10
1     479.00
2     340.00
3     282.40
4     406.00
5     300.00
6     374.00
7     253.30
8     195.10
9     269.00
10    329.30
11    250.70
12    250.70
13    345.30
14    379.30
15    275.00
16    215.20
17    300.00
18    304.68
19    323.00
20    243.00
21    364.20
22    282.00
23    300.00
24    246.00
25    334.50
26    250.00
27    241.00
28    304.68
29    280.00
30    380.30
31    243.00
Name: Calories, dtype: float64

In [20]:
print(df[df.duplicated()])

    Duration       Date  Pulse  Maxpulse  Calories
12        60 2020-12-12    100       120     250.7

In [18]:
print(df.drop_duplicates())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [21]:
print(df[df["Duration"] > 120])

   Duration       Date  Pulse  Maxpulse  Calories
7       450 2020-12-08    104       134     253.3

In [ ]:
import pandas as pd
df = pd.read_csv(r"c:\Users\BM\Downloads\data.csv")
df.loc[df["Duration"] > 120, "Duration"] = 45
print(df)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7         45  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [4]:
print(df.dropna(subset=["Date"]))

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7         45  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [5]:
print(df.assign(Date=pd.to_datetime(df["Date"], format="mixed")))

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7         45 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

data selection

In [6]:
print(df[df["Duration"] > 60])

Empty DataFrame
Columns: [Duration, Date, Pulse, Maxpulse, Calories]
Index: []

In [7]:
print(df[df["Pulse"] > 110])

    Duration          Date  Pulse  Maxpulse  Calories
1         60  '2020/12/02'    117       145     479.0
4         45  '2020/12/05'    117       148     406.0
23        60  '2020/12/23'    130       101     300.0

In [8]:
print(df[df["Calories"] > 350])

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
4         45  '2020/12/05'    117       148     406.0
6         60  '2020/12/07'    110       136     374.0
14        60  '2020/12/14'    104       132     379.3
21        60  '2020/12/21'    108       131     364.2
30        60  '2020/12/30'    102       129     380.3

In [9]:
print(df[(df["Pulse"] >= 100) & (df["Pulse"] <= 110)])

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7         45  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3

In [13]:
print(df[["Duration", "Calories"]])

    Duration  Calories
0         60     409.1
1         60     479.0
2         60     340.0
3         45     282.4
4         45     406.0
5         60     300.0
6         60     374.0
7         45     253.3
8         30     195.1
9         60     269.0
10        60     329.3
11        60     250.7
12        60     250.7
13        60     345.3
14        60     379.3
15        60     275.0
16        60     215.2
17        60     300.0
18        45       NaN
19        60     323.0
20        45     243.0
21        60     364.2
22        45     282.0
23        60     300.0
24        45     246.0
25        60     334.5
26        60     250.0
27        60     241.0
28        60       NaN
29        60     280.0
30        60     380.3
31        60     243.0

data analysis

In [14]:
average_pulse = df["Pulse"].mean()
print("average_pulse:", average_pulse)

average_pulse: 103.5

In [16]:
day_max_calories = df.loc[df["Calories"].idxmax(), "Date"]
print("day_max_calories:", day_max_calories)

day_max_calories: '2020/12/02'

In [21]:
import pandas as pd

# Assuming your Date column looks like 20201226
df['Date'] = pd.to_datetime(df['Date'], format='mixed')

# Now calculate total Calories burned in December
total_cal_december = df[df['Date'].dt.month == 12]['Calories'].sum()
print("Total Calories burned in December:", total_cal_december)

Total Calories burned in December: 8858.4

In [22]:
average_duration_workout = df["Duration"].mean()
print("average_duration_workout:", average_duration_workout)

average_duration_workout: 55.78125

In [23]:
max_maxpulse = df["Pulse"].max()
print("max_maxpulse:", max_maxpulse)

max_maxpulse: 130

sorting & grouping

In [27]:
sorted_by_calories = df.sort_values(by='Calories', ascending=False)
print("Dataset sorted by Calories burned (descending):", sorted_by_calories)

Dataset sorted by Calories burned (descending):     Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
0         60 2020-12-01    110       130     409.1
4         45 2020-12-05    117       148     406.0
30        60 2020-12-30    102       129     380.3
14        60 2020-12-14    104       132     379.3
6         60 2020-12-07    110       136     374.0
21        60 2020-12-21    108       131     364.2
13        60 2020-12-13    106       128     345.3
2         60 2020-12-03    103       135     340.0
25        60 2020-12-25    102       126     334.5
10        60 2020-12-11    103       147     329.3
19        60 2020-12-19    103       123     323.0
23        60 2020-12-23    130       101     300.0
5         60 2020-12-06    102       127     300.0
17        60 2020-12-17    100       120     300.0
3         45 2020-12-04    109       175     282.4
22        45        NaT    100       119     282.0
29        60 2020-12-29    100       132     280.0
15        60 2020-12-15     98       123     275.0
9         60 2020-12-10     98       124     269.0
7         45 2020-12-08    104       134     253.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
26        60 2020-12-26    100       120     250.0
24        45 2020-12-24    105       132     246.0
31        60 2020-12-31     92       115     243.0
20        45 2020-12-20     97       125     243.0
27        60 2020-12-27     92       118     241.0
16        60 2020-12-16     98       120     215.2
8         30 2020-12-09    109       133     195.1
18        45 2020-12-18     90       112       NaN
28        60 2020-12-28    103       132       NaN

In [29]:
sorted_by_pulse = df.sort_values(by='Pulse', ascending=True)
print("Dataset sorted by Pulse (ascending):", sorted_by_pulse)

Dataset sorted by Pulse (ascending):     Duration       Date  Pulse  Maxpulse  Calories
18        45 2020-12-18     90       112       NaN
27        60 2020-12-27     92       118     241.0
31        60 2020-12-31     92       115     243.0
20        45 2020-12-20     97       125     243.0
15        60 2020-12-15     98       123     275.0
9         60 2020-12-10     98       124     269.0
16        60 2020-12-16     98       120     215.2
11        60 2020-12-12    100       120     250.7
17        60 2020-12-17    100       120     300.0
22        45        NaT    100       119     282.0
29        60 2020-12-29    100       132     280.0
12        60 2020-12-12    100       120     250.7
26        60 2020-12-26    100       120     250.0
5         60 2020-12-06    102       127     300.0
30        60 2020-12-30    102       129     380.3
25        60 2020-12-25    102       126     334.5
28        60 2020-12-28    103       132       NaN
10        60 2020-12-11    103       147     329.3
2         60 2020-12-03    103       135     340.0
19        60 2020-12-19    103       123     323.0
7         45 2020-12-08    104       134     253.3
14        60 2020-12-14    104       132     379.3
24        45 2020-12-24    105       132     246.0
13        60 2020-12-13    106       128     345.3
21        60 2020-12-21    108       131     364.2
3         45 2020-12-04    109       175     282.4
8         30 2020-12-09    109       133     195.1
0         60 2020-12-01    110       130     409.1
6         60 2020-12-07    110       136     374.0
4         45 2020-12-05    117       148     406.0
1         60 2020-12-02    117       145     479.0
23        60 2020-12-23    130       101     300.0

In [33]:
average_pulse_by_duration = df.groupby('Duration')['Pulse'].mean().reset_index()
print("\nAverage Pulse by Duration:", average_pulse_by_duration)

Average Pulse by Duration:    Duration       Pulse
0        30  109.000000
1        45  103.142857
2        60  103.375000

In [31]:
avg_pulse_by_duration = df.groupby('Duration')['Pulse'].mean().reset_index()
print("\nAverage Pulse by Duration:")
print(avg_pulse_by_duration)

Average Pulse by Duration:
   Duration       Pulse
0        30  109.000000
1        45  103.142857
2        60  103.375000

In [34]:
top_5_calories = df.nlargest(5, 'Calories')
print("\nTop 5 records with highest Calories burned:")
print(top_5_calories)

Top 5 records with highest Calories burned:
    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
0         60 2020-12-01    110       130     409.1
4         45 2020-12-05    117       148     406.0
30        60 2020-12-30    102       129     380.3
14        60 2020-12-14    104       132     379.3

sorting & ranking

In [1]:
import pandas as pd
df = pd.read_csv(r"c:\Users\BM\Downloads\data.csv")
sorted_by_calories = df.sort_values(by='Calories', ascending=False)
print("\nDataset sorted by Calories burned (ascending):")
print(sorted_by_calories)

Dataset sorted by Calories burned (ascending):
    Duration          Date  Pulse  Maxpulse  Calories
1         60  '2020/12/02'    117       145     479.0
0         60  '2020/12/01'    110       130     409.1
4         45  '2020/12/05'    117       148     406.0
30        60  '2020/12/30'    102       129     380.3
14        60  '2020/12/14'    104       132     379.3
6         60  '2020/12/07'    110       136     374.0
21        60  '2020/12/21'    108       131     364.2
13        60  '2020/12/13'    106       128     345.3
2         60  '2020/12/03'    103       135     340.0
25        60  '2020/12/25'    102       126     334.5
10        60  '2020/12/11'    103       147     329.3
19        60  '2020/12/19'    103       123     323.0
23        60  '2020/12/23'    130       101     300.0
5         60  '2020/12/06'    102       127     300.0
17        60  '2020/12/17'    100       120     300.0
3         45  '2020/12/04'    109       175     282.4
22        45           NaN    100       119     282.0
29        60  '2020/12/29'    100       132     280.0
15        60  '2020/12/15'     98       123     275.0
9         60  '2020/12/10'     98       124     269.0
7        450  '2020/12/08'    104       134     253.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
26        60      20201226    100       120     250.0
24        45  '2020/12/24'    105       132     246.0
31        60  '2020/12/31'     92       115     243.0
20        45  '2020/12/20'     97       125     243.0
27        60  '2020/12/27'     92       118     241.0
16        60  '2020/12/16'     98       120     215.2
8         30  '2020/12/09'    109       133     195.1
18        45  '2020/12/18'     90       112       NaN
28        60  '2020/12/28'    103       132       NaN

In [ ]:
sorted_by_pulse = df.sort_values(by='Pulse', ascending=True)
print("\nDataset sorted by Pulse (descending):")
print(sorted_by_pulse)

Dataset sorted by Pulse (descending):
    Duration          Date  Pulse  Maxpulse  Calories
23        60  '2020/12/23'    130       101     300.0
1         60  '2020/12/02'    117       145     479.0
4         45  '2020/12/05'    117       148     406.0
6         60  '2020/12/07'    110       136     374.0
0         60  '2020/12/01'    110       130     409.1
3         45  '2020/12/04'    109       175     282.4
8         30  '2020/12/09'    109       133     195.1
21        60  '2020/12/21'    108       131     364.2
13        60  '2020/12/13'    106       128     345.3
24        45  '2020/12/24'    105       132     246.0
14        60  '2020/12/14'    104       132     379.3
7        450  '2020/12/08'    104       134     253.3
19        60  '2020/12/19'    103       123     323.0
2         60  '2020/12/03'    103       135     340.0
10        60  '2020/12/11'    103       147     329.3
28        60  '2020/12/28'    103       132       NaN
5         60  '2020/12/06'    102       127     300.0
30        60  '2020/12/30'    102       129     380.3
25        60  '2020/12/25'    102       126     334.5
12        60  '2020/12/12'    100       120     250.7
29        60  '2020/12/29'    100       132     280.0
26        60      20201226    100       120     250.0
11        60  '2020/12/12'    100       120     250.7
17        60  '2020/12/17'    100       120     300.0
22        45           NaN    100       119     282.0
9         60  '2020/12/10'     98       124     269.0
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
20        45  '2020/12/20'     97       125     243.0
27        60  '2020/12/27'     92       118     241.0
31        60  '2020/12/31'     92       115     243.0
18        45  '2020/12/18'     90       112       NaN

In [5]:
top_5_calories = df.nlargest(5, 'Calories')
print("\nTop 5 records with highest Calories burned:")
print(top_5_calories)

Top 5 records with highest Calories burned:
    Duration          Date  Pulse  Maxpulse  Calories
1         60  '2020/12/02'    117       145     479.0
0         60  '2020/12/01'    110       130     409.1
4         45  '2020/12/05'    117       148     406.0
30        60  '2020/12/30'    102       129     380.3
14        60  '2020/12/14'    104       132     379.3

In [6]:
top_5_long_workouts = df.nlargest(5, 'Duration')
print("\nTop 5 records with longest Duration:")
print(top_5_long_workouts)

Top 5 records with longest Duration:
   Duration          Date  Pulse  Maxpulse  Calories
7       450  '2020/12/08'    104       134     253.3
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
5        60  '2020/12/06'    102       127     300.0

In [9]:
df["Calories_ranking"] = df["Calories"].rank(ascending=False)
print(df["Calories_ranking"])

0      2.0
1      1.0
2      9.0
3     16.0
4      3.0
5     14.0
6      6.0
7     21.0
8     30.0
9     20.0
10    11.0
11    22.5
12    22.5
13     8.0
14     5.0
15    19.0
16    29.0
17    14.0
18     NaN
19    12.0
20    26.5
21     7.0
22    17.0
23    14.0
24    25.0
25    10.0
26    24.0
27    28.0
28     NaN
29    18.0
30     4.0
31    26.5
Name: Calories_ranking, dtype: float64

In [10]:
average_pulse = df["Pulse"].mean()
print("average_pulse:", average_pulse)

average_pulse: 103.5

In [11]:
average_duration = df["Duration"].mean()
print("average_duration:", average_duration)

average_duration: 68.4375

In [12]:
max_calories = df["Calories"].max()
print("max_calories:", max_calories)

max_calories: 479.0

In [13]:
min_pulse = df["Pulse"].min()
print("min_pulse:", min_pulse)

min_pulse: 90

In [18]:
total_calories_burned = df["Calories"].sum()
print("total_calories_burned:", total_calories_burned)

total_calories_burned: 9140.4

In [16]:
count_duration_60 = df[df["Duration"] > 60]
print("Number of workouts with Duration greater than 60 minutes:", count_duration_60)

Number of workouts with Duration greater than 60 minutes:    Duration          Date  Pulse  Maxpulse  Calories  Calories_ranking
7       450  '2020/12/08'    104       134     253.3              21.0

dataset & group by

In [19]:
avg_calories = df.groupby("Duration")["Calories"].mean()
print(avg_calories)

Duration
30     195.10000
45     291.88000
60     314.46087
450    253.30000
Name: Calories, dtype: float64

In [24]:
import pandas as pd
df = pd.read_csv(r"c:\Users\BM\Downloads\data.csv")
avg_pulse = df.groupby('Duration')['Pulse'].mean()
print(avg_pulse)

Duration
30     109.000
45     103.000
60     103.375
450    104.000
Name: Pulse, dtype: float64

In [25]:
max_pulse = df.groupby('Duration')['Pulse'].max()
print(max_pulse)

Duration
30     109
45     117
60     130
450    104
Name: Pulse, dtype: int64

In [27]:
work_count = df.groupby('Duration').size()
print(work_count)

Duration
30      1
45      6
60     24
450     1
dtype: int64

In [28]:
max_cal_day = df.loc[df['Calories'].idxmax(), ['Date', 'Calories']]
print(max_cal_day)

Date        '2020/12/02'
Calories           479.0
Name: 1, dtype: object

In [29]:
avg_workout_duration = df['Duration'].mean()
print(avg_workout_duration)

68.4375

In [30]:
max_pulse_workout = df.loc[df['Pulse'].idxmax()]
print(max_pulse_workout)

Duration              60
Date        '2020/12/23'
Pulse                130
Maxpulse             101
Calories           300.0
Name: 23, dtype: object

In [31]:
avg_cal_per_min = (df['Calories'] / df['Duration']).mean()
print("Average Calories burned per minute:", avg_cal_per_min)

Average Calories burned per minute: 5.3346888888888895

In [1]:
import pandas as pd
df = pd.read_csv(r"c:\Users\BM\Downloads\data.csv")
df[df.Pulse > 100]

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
10        60  '2020/12/11'    103       147     329.3
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
19        60  '2020/12/19'    103       123     323.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
28        60  '2020/12/28'    103       132       NaN
30        60  '2020/12/30'    102       129     380.3