In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import pandas as pd

In [10]:
df = pd.read_csv(r"c:\Users\BM\Downloads\student_data_clean.csv")
df

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,Attendance_Rate,Scholarship,Admission_Date,Midterm_Marks,Final_Marks,City,Study_Hours_Per_Day,Fees_Paid
0,1001,Student_0,24,Other,Math,3,NaN,61.0,False,2021-09-11,26,33,Multan,10,NaN
1,1002,Student_1,21,Female,EE,1,3.94,98.0,False,2020-01-26,0,39,Lahore,5,Installment
2,1003,Student_2,22,Other,EE,5,2.44,66.0,False,2022-08-14,20,46,Faisalabad,7,Full
3,1004,Student_3,24,Male,EE,4,3.47,91.0,False,2021-02-24,19,14,Faisalabad,8,Full
4,1005,Student_4,20,Male,CS,2,3.53,79.0,False,2021-10-24,12,10,Karachi,3,Installment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,1026,Student_25,18,Other,Math,8,2.01,89.0,False,2022-05-23,3,17,Multan,9,Installment
1026,1027,Student_26,21,Other,BBA,6,3.87,57.0,False,2021-02-12,15,13,Karachi,8,Full
1027,1028,Student_27,19,Female,Math,1,3.64,89.0,False,2020-10-26,7,17,Islamabad,8,Installment
1028,1029,Student_28,23,Male,EE,5,3.62,93.0,True,2022-06-26,15,27,Islamabad,5,Pending
1029,1030,Student_29,22,Other,Math,2,3.77,72.0,False,2021-08-24,26,23,Islamabad,9,Full

In [14]:
df.isnull().sum()

Student_ID              0
Name                    0
Age                     0
Gender                  0
Department              0
Semester                0
CGPA                   51
Attendance_Rate        31
Scholarship             0
Admission_Date          0
Midterm_Marks           0
Final_Marks             0
City                    0
Study_Hours_Per_Day     0
Fees_Paid              22
dtype: int64

In [16]:
df.dropna()

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,Attendance_Rate,Scholarship,Admission_Date,Midterm_Marks,Final_Marks,City,Study_Hours_Per_Day,Fees_Paid
1,1002,Student_1,21,Female,EE,1,3.94,98.0,False,2020-01-26,0,39,Lahore,5,Installment
2,1003,Student_2,22,Other,EE,5,2.44,66.0,False,2022-08-14,20,46,Faisalabad,7,Full
3,1004,Student_3,24,Male,EE,4,3.47,91.0,False,2021-02-24,19,14,Faisalabad,8,Full
4,1005,Student_4,20,Male,CS,2,3.53,79.0,False,2021-10-24,12,10,Karachi,3,Installment
6,1007,Student_6,22,Female,Math,3,2.06,68.0,False,2022-05-02,8,23,Islamabad,2,Full
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,1026,Student_25,18,Other,Math,8,2.01,89.0,False,2022-05-23,3,17,Multan,9,Installment
1026,1027,Student_26,21,Other,BBA,6,3.87,57.0,False,2021-02-12,15,13,Karachi,8,Full
1027,1028,Student_27,19,Female,Math,1,3.64,89.0,False,2020-10-26,7,17,Islamabad,8,Installment
1028,1029,Student_28,23,Male,EE,5,3.62,93.0,True,2022-06-26,15,27,Islamabad,5,Pending
1029,1030,Student_29,22,Other,Math,2,3.77,72.0,False,2021-08-24,26,23,Islamabad,9,Full

In [4]:
import pandas as pd
df = pd.read_csv(r"c:\Users\BM\Downloads\student_data_clean.csv")
df.isnull().sum()

Student_ID              0
Name                    0
Age                     0
Gender                  0
Department              0
Semester                0
CGPA                   51
Attendance_Rate        31
Scholarship             0
Admission_Date          0
Midterm_Marks           0
Final_Marks             0
City                    0
Study_Hours_Per_Day     0
Fees_Paid              22
dtype: int64

In [18]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1025     True
1026     True
1027     True
1028     True
1029     True
Length: 1030, dtype: bool

In [19]:
df.drop_duplicates()

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,Attendance_Rate,Scholarship,Admission_Date,Midterm_Marks,Final_Marks,City,Study_Hours_Per_Day,Fees_Paid
0,1001,Student_0,24,Other,Math,3,NaN,61.0,False,2021-09-11,26,33,Multan,10,NaN
1,1002,Student_1,21,Female,EE,1,3.94,98.0,False,2020-01-26,0,39,Lahore,5,Installment
2,1003,Student_2,22,Other,EE,5,2.44,66.0,False,2022-08-14,20,46,Faisalabad,7,Full
3,1004,Student_3,24,Male,EE,4,3.47,91.0,False,2021-02-24,19,14,Faisalabad,8,Full
4,1005,Student_4,20,Male,CS,2,3.53,79.0,False,2021-10-24,12,10,Karachi,3,Installment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1996,Student_995,23,Male,Math,3,3.88,81.0,False,2021-01-02,23,10,Islamabad,5,Full
996,1997,Student_996,18,Other,EE,7,3.55,89.0,False,2020-07-30,4,19,Multan,4,Installment
997,1998,Student_997,24,Female,Math,6,2.26,62.0,True,2021-07-30,23,47,Islamabad,8,Pending
998,1999,Student_998,21,Other,BBA,3,2.70,69.0,False,2022-08-18,23,8,Karachi,7,Installment
999,2000,Student_999,23,Female,BBA,3,2.87,84.0,False,2020-07-27,5,1,Lahore,6,Pending

In [20]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'Semester', 'CGPA',
       'Attendance_Rate', 'Scholarship', 'Admission_Date', 'Midterm_Marks',
       'Final_Marks', 'City', 'Study_Hours_Per_Day', 'Fees_Paid'],
      dtype='str')

In [22]:
pt = pd.pivot_table(df, values='Midterm_Marks', index='Scholarship', columns='Attendance_Rate')
pt

Attendance_Rate,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0,...,90.0,91.0,92.0,93.0,94.0,95.0,96.0,97.0,98.0,99.0
Scholarship,,,,,,,,,,,,,,,,,,,,,
False,13.5,11.5,16.142857,16.526316,15.733333,18.857143,15.916667,16.0,19.230769,9.800000,...,11.333333,15.75,15.857143,12.266667,15.571429,17.875000,19.0,14.8,12.4375,13.454545
True,9.2,14.8,6.333333,13.000000,9.500000,18.000000,26.000000,29.0,12.000000,11.333333,...,8.250000,20.00,18.500000,17.428571,16.400000,8.666667,20.5,27.0,22.2500,13.500000

In [6]:
import pandas as pd
df = pd.read_csv(r"c:\Users\BM\Downloads\student_data_clean.csv")
pt = pd.pivot_table(df, values='Scholarship', index='Department', columns='Semester', aggfunc='count')
pt

Semester     1   2   3   4   5   6   7   8
Department
BBA         27  19  33  26  30  20  23  29
CS          29  25  17  29  29  26  22  21
EE          25   9  21  26  25  19  23  30
Math        33  25  37  33  24  26  28  29
Physics     23  31  37  26  23  32  25  15